const checkoutSession = {
  id: "cs_test_a1XWvtiphyfRUspwGMRoTC1GtKoR3jlEhTybrJlgCHxZiFwoET4TD9JuXB",
  object: "checkout.session",
  adaptive_pricing: { enabled: true },
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 150,
  amount_total: 150,
  automatic_tax: { enabled: false, liability: null, status: null },
  billing_address_collection: null,
  cancel_url:
    "http://localhost:3000/dreamwalker-studios/settings/payments/checkout?canceled=true",
  client_reference_id: null,
  client_secret: null,
  collected_information: null,
  consent: null,
  consent_collection: null,
  created: 1744932704,
  currency: "usd",
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null,
  },
  customer: null,
  customer_creation: "if_required",
  customer_details: {
    address: {
      city: null,
      country: "US",
      line1: null,
      line2: null,
      postal_code: "48109",
      state: null,
    },
    email: "ahunn@umich.edu",
    name: "Andrew Hunn",
    phone: null,
    tax_exempt: "none",
    tax_ids: [],
  },
  customer_email: null,
  discounts: [],
  expires_at: 1745019104,
  invoice: null,
  invoice_creation: {
    enabled: false,
    invoice_data: {
      account_tax_ids: null,
      custom_fields: null,
      description: null,
      footer: null,
      issuer: null,
      metadata: {},
      rendering_options: null,
    },
  },
  livemode: false,
  locale: null,
  metadata: { orderId: "cm9k96xx800012gd9p8zd59yh" },
  mode: "payment",
  payment_intent: "pi_3RF1ueCa1sm4MagI0dkAVdm2",
  payment_link: null,
  payment_method_collection: "if_required",
  payment_method_configuration_details: null,
  payment_method_options: { card: { request_three_d_secure: "automatic" } },
  payment_method_types: ["card"],
  payment_status: "paid",
  permissions: null,
  phone_number_collection: { enabled: false },
  recovered_from: null,
  saved_payment_method_options: null,
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_options: [],
  status: "complete",
  submit_type: null,
  subscription: null,
  success_url:
    "http://localhost:3000/dreamwalker-studios/settings/payments/checkout?session_id={CHECKOUT_SESSION_ID}",
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  ui_mode: "hosted",
  url: null,
  wallet_options: null,
};
